/*********************************************************************************
* BTI425 – Assignment 2
* I declare that this assignment is my own work in accordance with Seneca Academic Policy.
* No part of this assignment has been copied manually or electronically from any other source
* (including web sites) or distributed to other students.
*
* Name: Daniel Thai  Student ID: 151900198  Date: 2/23/2021
*
********************************************************************************/
import React from 'react';
import { LinkContainer } from 'react-router-bootstrap';
import './Page.css';
import Pagination from 'react-bootstrap/Pagination';

/**
 * This is the page navigation component, used by the Page component. It expects
 * two props, the pageNum indicating the current page and the number of pages.
 * Pages are indexed starting at 1.
 */
class PageNav extends React.Component
{
    constructor(props)
    {
        super(props);
        this.pageEndStyle = { backgroundColor: "white" };
    }

    render()
    {
        return(
            <Pagination className="text-center justify-content-center">
                {/* The previous page button. Link will be disabled when the current page is at the beginning */}
                {(this.props.pageNum > 1)?
                    <LinkContainer key="back" to={`/page/${parseInt(this.props.pageNum)-1}`} style={this.pageEndStyle}>
                        <Pagination.Item style={this.pageEndStyle}>{"<<"}</Pagination.Item>
                    </LinkContainer>
                :<Pagination.Item style={this.pageEndStyle}>{"<<"}</Pagination.Item>}
                {/* Page buttons, generated by making an array the length of the number pages. Pagenumbers generated by using the key. 
                    Will be indexed at zero, so page link and display should be added by 1*/}
                {[...Array(this.props.pages).keys()].map(number=>
                    <LinkContainer key={number+1} to={`/page/${number+1}`}>
                        <Pagination.Item active={number+1 === this.props.pageNum}>
                            {number+1}
                        </Pagination.Item>
                    </LinkContainer>)}
                {/* The next page button. Link will be disabled when the current page is at the end */}
                {(this.props.pageNum < this.props.pages)?
                    <LinkContainer key="next" to={`/page/${parseInt(this.props.pageNum)+1}`} style={this.pageEndStyle}>
                        <Pagination.Item style={this.pageEndStyle}>{">>"}</Pagination.Item>
                    </LinkContainer>
                :<Pagination.Item key="next" style={this.pageEndStyle}>{">>"}</Pagination.Item>}
            </Pagination>
        );
    }
}

export default PageNav;